pasta=("Pasta Arrabiata","Italian",20,"Medium")
biryani=("Chicken Biryani","Indian",45,"Hard")
print("Recipe:", pasta)
print("Name: ",pasta[0])
print("Cuisine: ",pasta[1])
print("Difficulty: ",pasta[-1])
allrecipes=(pasta,biryani)
print("\nFirst Recipe name: ",allrecipes[0][0])
print("Second Recipe time: ",allrecipes[1][2],"mins")
print("Pasta details: ",allrecipes[1:3])
print("\nPasta details: ")
for detail in pasta:
    print('-',detail)
pastaingredients={"Pasta","Tomato","chilli","garlic","salt","olive oil"}
biryaniingredients={"Rice","Chicken","garlic","onion","tomato","spices"}
print("\nPasta Ingredients: ",pastaingredients)
print("Biryani ingredients: ",biryaniingredients)
print("number of ingredients in pasta recipe: ",len(pastaingredients))
pastaingredients.add("Parmesan")
pastaingredients.discard("Chilli")
print("\nUpgraded ingredients in pasta recipe: ",pastaingredients)
allingredients=pastaingredients.union(biryaniingredients)
common=pastaingredients.intersection(biryaniingredients)
onlyppasta=pastaingredients.difference(biryaniingredients)
uniquetoeach=pastaingredients.symmetric_difference(biryaniingredients)
print("\n All ingredients: ",allingredients)
print("Common: ",common)
print("Only in pasta: ",onlyppasta)
print("Unique to each: ",uniquetoeach)