stuprof=("Arham","Grade 4","Flamingo",6)
print("Student profile: ",stuprof)
name=stuprof[0]
grade=stuprof[1]
section=stuprof[2]
ts=stuprof[3]
print("Name: ",name)
print("Grade: ",grade)
print("Section: ",section)
print("Total subjects: ",ts)
print("First 2 details: ",stuprof[0:2])
mondaysubs={"Maths","English","History","Geography","Science"}
tuesdaysubs={"Maths","English","Geography","Library","P.E"}
mondaysubs.add("ICT")
print("After adding ICT to monday: ",mondaysubs)
mondaysubs.discard("ICT")
print("After discarding ICT from monday: ",mondaysubs)
tuesdaysubs.add("Bangla")
print("After adding Bangla to tuesday: ",tuesdaysubs)
tuesdaysubs.discard("Bangla")
print("After discarding Bangla from truesday: ",tuesdaysubs)
allsubs=mondaysubs.union(tuesdaysubs)
commonsubs=mondaysubs.intersection(tuesdaysubs)
onlymonday=mondaysubs.difference(tuesdaysubs)
onlytuesday=tuesdaysubs.difference(mondaysubs)
diffsubs=mondaysubs.symmetric_difference(tuesdaysubs)
print("All subjects: ",allsubs)
print("Common subjects: ",commonsubs)
print("Monday Subjects: ",onlymonday)
print("Only Tuesday: ",onlytuesday)
print("Different Subjects: ",diffsubs)
print("\n FULL SUMMARY")
print("\nName: ",name)
print("Grade: ",grade)
print("Section: ",section)
print("Total subjects: ",ts)
print("First 2 details: ",stuprof[0:2])
print("All subjects: ",allsubs)
print("Common subjects: ",commonsubs)
print("Monday Subjects: ",onlymonday)
print("Only Tuesday: ",onlytuesday)
print("Different Subjects: ",diffsubs)
print("********************************************************************************************************************************************************************************")
print("                                                                                        THANK YOU")
print("********************************************************************************************************************************************************************************")